# Generated by Django 2.2.7 on 2019-11-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AuthUser')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SurveySurvey')),
            ],
        ),
    ]
